// // Generated by llvm2cpp - DO NOT MODIFY!
//
// #include <llvm/Pass.h>
// #include <llvm/ADT/SmallVector.h>
// #include <llvm/IR/Verifier.h>
// #include <llvm/IR/BasicBlock.h>
// #include <llvm/IR/CallingConv.h>
// #include <llvm/IR/Constants.h>
// #include <llvm/IR/DerivedTypes.h>
// #include <llvm/IR/Function.h>
// #include <llvm/IR/GlobalVariable.h>
// #include <llvm/IR/IRPrintingPasses.h>
// #include <llvm/IR/InlineAsm.h>
// #include <llvm/IR/Instructions.h>
// #include <llvm/IR/LLVMContext.h>
// #include <llvm/IR/LegacyPassManager.h>
// #include <llvm/IR/Module.h>
// #include <llvm/Support/FormattedStream.h>
// #include <llvm/Support/MathExtras.h>
// #include <algorithm>
// using namespace llvm::legacy;
// using namespace llvm;
// Module* makeLLVMModule();
//
// // int main(int argc, char**argv) {
// //   Module* Mod = makeLLVMModule();
// //   Mod->dump();
// //   return 0;
// // }
//
//
// Module* makeLLVMModule() {
//  //   printf("what\n");
//  // Module Construction
//  Module* mod = new Module("util.bc", getGlobalContext());
//  mod->setDataLayout("");
//  mod->setTargetTriple("x86_64-unknown-linux-gnu");
//
//  // Type Definitions
//  StructType *StructTy_struct__IO_FILE = mod->getTypeByName("struct._IO_FILE");
//  if (!StructTy_struct__IO_FILE) {
//  StructTy_struct__IO_FILE = StructType::create(mod->getContext(), "struct._IO_FILE");
//  }
//  std::vector<Type*>StructTy_struct__IO_FILE_fields;
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 32));
//  PointerType* PointerTy_2 = PointerType::get(IntegerType::get(mod->getContext(), 8), 0);
//
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructType *StructTy_struct__IO_marker = mod->getTypeByName("struct._IO_marker");
//  if (!StructTy_struct__IO_marker) {
//  StructTy_struct__IO_marker = StructType::create(mod->getContext(), "struct._IO_marker");
//  }
//  std::vector<Type*>StructTy_struct__IO_marker_fields;
//  PointerType* PointerTy_3 = PointerType::get(StructTy_struct__IO_marker, 0);
//
//  StructTy_struct__IO_marker_fields.push_back(PointerTy_3);
//  PointerType* PointerTy_1 = PointerType::get(StructTy_struct__IO_FILE, 0);
//
//  StructTy_struct__IO_marker_fields.push_back(PointerTy_1);
//  StructTy_struct__IO_marker_fields.push_back(IntegerType::get(mod->getContext(), 32));
//  if (StructTy_struct__IO_marker->isOpaque()) {
//  StructTy_struct__IO_marker->setBody(StructTy_struct__IO_marker_fields, /*isPacked=*/false);
//  }
//
//
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_3);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_1);
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 32));
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 32));
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 64));
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 16));
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 8));
//  ArrayType* ArrayTy_4 = ArrayType::get(IntegerType::get(mod->getContext(), 8), 1);
//
//  StructTy_struct__IO_FILE_fields.push_back(ArrayTy_4);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 64));
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(PointerTy_2);
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 64));
//  StructTy_struct__IO_FILE_fields.push_back(IntegerType::get(mod->getContext(), 32));
//  ArrayType* ArrayTy_5 = ArrayType::get(IntegerType::get(mod->getContext(), 8), 20);
//
//  StructTy_struct__IO_FILE_fields.push_back(ArrayTy_5);
//  if (StructTy_struct__IO_FILE->isOpaque()) {
//  StructTy_struct__IO_FILE->setBody(StructTy_struct__IO_FILE_fields, /*isPacked=*/false);
//  }
//
//
//  PointerType* PointerTy_0 = PointerType::get(PointerTy_1, 0);
//
//  ArrayType* ArrayTy_6 = ArrayType::get(IntegerType::get(mod->getContext(), 8), 54);
//
//  PointerType* PointerTy_7 = PointerType::get(ArrayTy_6, 0);
//
//  std::vector<Type*>FuncTy_8_args;
//  FuncTy_8_args.push_back(PointerTy_2);
//  FunctionType* FuncTy_8 = FunctionType::get(
//   /*Result=*/Type::getVoidTy(mod->getContext()),
//   /*Params=*/FuncTy_8_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_9 = PointerType::get(PointerTy_2, 0);
//
//  std::vector<Type*>FuncTy_11_args;
//  FuncTy_11_args.push_back(PointerTy_2);
//  FunctionType* FuncTy_11 = FunctionType::get(
//   /*Result=*/IntegerType::get(mod->getContext(), 32),
//   /*Params=*/FuncTy_11_args,
//   /*isVarArg=*/true);
//
//  PointerType* PointerTy_10 = PointerType::get(FuncTy_11, 0);
//
//  std::vector<Type*>FuncTy_13_args;
//  FuncTy_13_args.push_back(IntegerType::get(mod->getContext(), 32));
//  FunctionType* FuncTy_13 = FunctionType::get(
//   /*Result=*/Type::getVoidTy(mod->getContext()),
//   /*Params=*/FuncTy_13_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_12 = PointerType::get(FuncTy_13, 0);
//
//  StructType *StructTy_struct_Object = mod->getTypeByName("struct.Object");
//  if (!StructTy_struct_Object) {
//  StructTy_struct_Object = StructType::create(mod->getContext(), "struct.Object");
//  }
//  std::vector<Type*>StructTy_struct_Object_fields;
//  StructType *StructTy_union_anon = mod->getTypeByName("union.anon");
//  if (!StructTy_union_anon) {
//  StructTy_union_anon = StructType::create(mod->getContext(), "union.anon");
//  }
//  std::vector<Type*>StructTy_union_anon_fields;
//  PointerType* PointerTy_14 = PointerType::get(StructTy_struct_Object, 0);
//
//  StructTy_union_anon_fields.push_back(PointerTy_14);
//  if (StructTy_union_anon->isOpaque()) {
//  StructTy_union_anon->setBody(StructTy_union_anon_fields, /*isPacked=*/false);
//  }
//
//  StructTy_struct_Object_fields.push_back(StructTy_union_anon);
//  StructType *StructTy_union_anon_0 = mod->getTypeByName("union.anon.0");
//  if (!StructTy_union_anon_0) {
//  StructTy_union_anon_0 = StructType::create(mod->getContext(), "union.anon.0");
//  }
//  std::vector<Type*>StructTy_union_anon_0_fields;
//  StructTy_union_anon_0_fields.push_back(IntegerType::get(mod->getContext(), 64));
//  if (StructTy_union_anon_0->isOpaque()) {
//  StructTy_union_anon_0->setBody(StructTy_union_anon_0_fields, /*isPacked=*/false);
//  }
//
//  StructTy_struct_Object_fields.push_back(StructTy_union_anon_0);
//  if (StructTy_struct_Object->isOpaque()) {
//  StructTy_struct_Object->setBody(StructTy_struct_Object_fields, /*isPacked=*/false);
//  }
//
//
//  std::vector<Type*>FuncTy_15_args;
//  FunctionType* FuncTy_15 = FunctionType::get(
//   /*Result=*/PointerTy_14,
//   /*Params=*/FuncTy_15_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_16 = PointerType::get(PointerTy_14, 0);
//
//  PointerType* PointerTy_17 = PointerType::get(IntegerType::get(mod->getContext(), 64), 0);
//
//  std::vector<Type*>FuncTy_19_args;
//  FuncTy_19_args.push_back(PointerTy_9);
//  FuncTy_19_args.push_back(PointerTy_17);
//  FuncTy_19_args.push_back(PointerTy_1);
//  FunctionType* FuncTy_19 = FunctionType::get(
//   /*Result=*/IntegerType::get(mod->getContext(), 64),
//   /*Params=*/FuncTy_19_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_18 = PointerType::get(FuncTy_19, 0);
//
//  std::vector<Type*>FuncTy_21_args;
//  FuncTy_21_args.push_back(IntegerType::get(mod->getContext(), 64));
//  FunctionType* FuncTy_21 = FunctionType::get(
//   /*Result=*/PointerTy_2,
//   /*Params=*/FuncTy_21_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_20 = PointerType::get(FuncTy_21, 0);
//
//  PointerType* PointerTy_22 = PointerType::get(StructTy_union_anon, 0);
//
//  PointerType* PointerTy_23 = PointerType::get(IntegerType::get(mod->getContext(), 32), 0);
//
//  PointerType* PointerTy_24 = PointerType::get(StructTy_union_anon_0, 0);
//
//  std::vector<Type*>FuncTy_26_args;
//  FuncTy_26_args.push_back(PointerTy_2);
//  FunctionType* FuncTy_26 = FunctionType::get(
//   /*Result=*/IntegerType::get(mod->getContext(), 32),
//   /*Params=*/FuncTy_26_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_25 = PointerType::get(FuncTy_26, 0);
//
//  std::vector<Type*>FuncTy_27_args;
//  FuncTy_27_args.push_back(PointerTy_14);
//  FuncTy_27_args.push_back(PointerTy_14);
//  FunctionType* FuncTy_27 = FunctionType::get(
//   /*Result=*/PointerTy_14,
//   /*Params=*/FuncTy_27_args,
//   /*isVarArg=*/false);
//
//  std::vector<Type*>FuncTy_29_args;
//  FuncTy_29_args.push_back(PointerTy_2);
//  FunctionType* FuncTy_29 = FunctionType::get(
//   /*Result=*/IntegerType::get(mod->getContext(), 64),
//   /*Params=*/FuncTy_29_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_28 = PointerType::get(FuncTy_29, 0);
//
//  std::vector<Type*>FuncTy_31_args;
//  FuncTy_31_args.push_back(PointerTy_2);
//  FuncTy_31_args.push_back(PointerTy_2);
//  FunctionType* FuncTy_31 = FunctionType::get(
//   /*Result=*/PointerTy_2,
//   /*Params=*/FuncTy_31_args,
//   /*isVarArg=*/false);
//
//  PointerType* PointerTy_30 = PointerType::get(FuncTy_31, 0);
//
//  PointerType* PointerTy_32 = PointerType::get(FuncTy_27, 0);
//
//  PointerType* PointerTy_33 = PointerType::get(FuncTy_8, 0);
//
//
//  // Function Declarations
//
//  Function* func_error = mod->getFunction("error");
//  if (!func_error) {
//  func_error = Function::Create(
//   /*Type=*/FuncTy_8,
//   /*Linkage=*/GlobalValue::ExternalLinkage,
//   /*Name=*/"error", mod);
//  func_error->setCallingConv(CallingConv::C);
//  }
//  AttributeSet func_error_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoUnwind);
//     B.addAttribute(Attribute::UWTable);
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   func_error_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  func_error->setAttributes(func_error_PAL);
//
//  Function* func_printf = mod->getFunction("printf");
//  if (!func_printf) {
//  func_printf = Function::Create(
//   /*Type=*/FuncTy_11,
//   /*Linkage=*/GlobalValue::ExternalLinkage,
//   /*Name=*/"printf", mod); // (external, no body)
//  func_printf->setCallingConv(CallingConv::C);
//  }
//  AttributeSet func_printf_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   func_printf_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  func_printf->setAttributes(func_printf_PAL);
//
//  Function* func_exit = mod->getFunction("exit");
//  if (!func_exit) {
//  func_exit = Function::Create(
//   /*Type=*/FuncTy_13,
//   /*Linkage=*/GlobalValue::ExternalLinkage,
//   /*Name=*/"exit", mod); // (external, no body)
//  func_exit->setCallingConv(CallingConv::C);
//  }
//  AttributeSet func_exit_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoReturn);
//     B.addAttribute(Attribute::NoUnwind);
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   func_exit_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  func_exit->setAttributes(func_exit_PAL);
//
//  Function* func_readLine = mod->getFunction("readLine");
//  if (!func_readLine) {
//  func_readLine = Function::Create(
//   /*Type=*/FuncTy_15,
//   /*Linkage=*/GlobalValue::ExternalLinkage,
//   /*Name=*/"readLine", mod);
//  func_readLine->setCallingConv(CallingConv::C);
//  }
//  AttributeSet func_readLine_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoUnwind);
//     B.addAttribute(Attribute::UWTable);
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   func_readLine_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  func_readLine->setAttributes(func_readLine_PAL);
//
//  Function* func_getline = mod->getFunction("getline");
//  if (!func_getline) {
//  func_getline = Function::Create(
//   /*Type=*/FuncTy_19,
//   /*Linkage=*/GlobalValue::ExternalLinkage,
//   /*Name=*/"getline", mod); // (external, no body)
//  func_getline->setCallingConv(CallingConv::C);
//  }
//  AttributeSet func_getline_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   func_getline_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  func_getline->setAttributes(func_getline_PAL);
//
//  Function* func_malloc = mod->getFunction("malloc");
//  if (!func_malloc) {
//  func_malloc = Function::Create(
//   /*Type=*/FuncTy_21,
//   /*Linkage=*/GlobalValue::ExternalLinkage,
//   /*Name=*/"malloc", mod); // (external, no body)
//  func_malloc->setCallingConv(CallingConv::C);
//  }
//  AttributeSet func_malloc_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoAlias);
//     PAS = AttributeSet::get(mod->getContext(), 0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_malloc_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_malloc->setAttributes(func_malloc_PAL);
//
// Function* func_readInt = mod->getFunction("readInt");
// if (!func_readInt) {
// func_readInt = Function::Create(
//  /*Type=*/FuncTy_15,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"readInt", mod);
// func_readInt->setCallingConv(CallingConv::C);
// }
// AttributeSet func_readInt_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    B.addAttribute(Attribute::UWTable);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_readInt_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_readInt->setAttributes(func_readInt_PAL);
//
// Function* func_atoi = mod->getFunction("atoi");
// if (!func_atoi) {
// func_atoi = Function::Create(
//  /*Type=*/FuncTy_26,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"atoi", mod); // (external, no body)
// func_atoi->setCallingConv(CallingConv::C);
// }
// AttributeSet func_atoi_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    B.addAttribute(Attribute::ReadOnly);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_atoi_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_atoi->setAttributes(func_atoi_PAL);
//
// Function* func_add_str = mod->getFunction("add_str");
// if (!func_add_str) {
// func_add_str = Function::Create(
//  /*Type=*/FuncTy_27,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"add_str", mod);
// func_add_str->setCallingConv(CallingConv::C);
// }
// AttributeSet func_add_str_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    B.addAttribute(Attribute::UWTable);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_add_str_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_add_str->setAttributes(func_add_str_PAL);
//
// Function* func_strlen = mod->getFunction("strlen");
// if (!func_strlen) {
// func_strlen = Function::Create(
//  /*Type=*/FuncTy_29,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"strlen", mod); // (external, no body)
// func_strlen->setCallingConv(CallingConv::C);
// }
// AttributeSet func_strlen_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    B.addAttribute(Attribute::ReadOnly);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_strlen_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_strlen->setAttributes(func_strlen_PAL);
//
// Function* func_strcpy = mod->getFunction("strcpy");
// if (!func_strcpy) {
// func_strcpy = Function::Create(
//  /*Type=*/FuncTy_31,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"strcpy", mod); // (external, no body)
// func_strcpy->setCallingConv(CallingConv::C);
// }
// AttributeSet func_strcpy_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_strcpy_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_strcpy->setAttributes(func_strcpy_PAL);
//
// Function* func_strcat = mod->getFunction("strcat");
// if (!func_strcat) {
// func_strcat = Function::Create(
//  /*Type=*/FuncTy_31,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"strcat", mod); // (external, no body)
// func_strcat->setCallingConv(CallingConv::C);
// }
// AttributeSet func_strcat_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_strcat_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_strcat->setAttributes(func_strcat_PAL);
//
// Function* func_add_int = mod->getFunction("add_int");
// if (!func_add_int) {
// func_add_int = Function::Create(
//  /*Type=*/FuncTy_27,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"add_int", mod);
// func_add_int->setCallingConv(CallingConv::C);
// }
// AttributeSet func_add_int_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    B.addAttribute(Attribute::UWTable);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_add_int_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_add_int->setAttributes(func_add_int_PAL);
//
// Function* func_add_any = mod->getFunction("add_any");
// if (!func_add_any) {
// func_add_any = Function::Create(
//  /*Type=*/FuncTy_27,
//  /*Linkage=*/GlobalValue::ExternalLinkage,
//  /*Name=*/"add_any", mod);
// func_add_any->setCallingConv(CallingConv::C);
// }
// AttributeSet func_add_any_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    B.addAttribute(Attribute::UWTable);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  func_add_any_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// func_add_any->setAttributes(func_add_any_PAL);
//
// // Global Variable Declarations
//
//
// GlobalVariable* gvar_ptr_stdin = new GlobalVariable(/*Module=*/*mod,
// /*Type=*/PointerTy_1,
// /*isConstant=*/false,
// /*Linkage=*/GlobalValue::ExternalLinkage,
// /*Initializer=*/0,
// /*Name=*/"stdin");
// gvar_ptr_stdin->setAlignment(8);
//
// GlobalVariable* gvar_array__str = new GlobalVariable(/*Module=*/*mod,
// /*Type=*/ArrayTy_6,
// /*isConstant=*/true,
// /*Linkage=*/GlobalValue::PrivateLinkage,
// /*Initializer=*/0, // has initializer, specified below
// /*Name=*/".str");
// gvar_array__str->setAlignment(1);
//
// // Constant Definitions
// Constant *const_array_34 = ConstantDataArray::getString(mod->getContext(), "Binop can only be applied to expressions of same type", true);
// ConstantInt* const_int32_35 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("1"), 10));
// ConstantInt* const_int32_36 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("-1"), 10));
// ConstantPointerNull* const_ptr_37 = ConstantPointerNull::get(PointerTy_17);
// ConstantInt* const_int64_38 = ConstantInt::get(mod->getContext(), APInt(64, StringRef("16"), 10));
// ConstantInt* const_int32_39 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("0"), 10));
// ConstantInt* const_int32_40 = ConstantInt::get(mod->getContext(), APInt(32, StringRef("2"), 10));
// ConstantInt* const_int64_41 = ConstantInt::get(mod->getContext(), APInt(64, StringRef("1"), 10));
// std::vector<Constant*> const_ptr_42_indices;
// const_ptr_42_indices.push_back(const_int32_39);
// const_ptr_42_indices.push_back(const_int32_39);
//
// //Constant* const_ptr_42 = ConstantExpr::getGetElementPtr(IntegerType::get(mod->getContext(), 8) , gvar_array__str, ArrayRef<Constant*>(const_ptr_42_indices));
// ConstantPointerNull* const_ptr_43 = ConstantPointerNull::get(PointerTy_14);
//
// // Global Variable Definitions
// gvar_array__str->setInitializer(const_array_34);
//
// // Function Definitions
//
// // Function: error (func_error)
// {
//  Function::arg_iterator args = func_error->arg_begin();
//  Value* ptr_msg = &(*args++);
//  ptr_msg->setName("msg");
//
//  BasicBlock* label_44 = BasicBlock::Create(mod->getContext(), "",func_error,0);
//  BasicBlock* label_45 = BasicBlock::Create(mod->getContext(), "",func_error,0);
//
//  // Block  (label_44)
//  AllocaInst* ptr_46 = new AllocaInst(PointerTy_2, "", label_44);
//  ptr_46->setAlignment(8);
//  StoreInst* void_47 = new StoreInst(ptr_msg, ptr_46, false, label_44);
//  void_47->setAlignment(8);
//  LoadInst* ptr_48 = new LoadInst(ptr_46, "", false, label_44);
//  ptr_48->setAlignment(8);
//  CallInst* int32_49 = CallInst::Create(func_printf, ptr_48, "", label_44);
//  int32_49->setCallingConv(CallingConv::C);
//  int32_49->setTailCall(false);
//  AttributeSet int32_49_PAL;
//  int32_49->setAttributes(int32_49_PAL);
//
//  CallInst* void_50 = CallInst::Create(func_exit, const_int32_36, "", label_44);
//  void_50->setCallingConv(CallingConv::C);
//  void_50->setTailCall(false);
//  AttributeSet void_50_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoReturn);
//     B.addAttribute(Attribute::NoUnwind);
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   void_50_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  void_50->setAttributes(void_50_PAL);
//
//  new UnreachableInst(mod->getContext(), label_44);
//
//  // Block  (label_45)
//  ReturnInst::Create(mod->getContext(), label_45);
//
// }
//
// // Function: readLine (func_readLine)
// {
//
//  BasicBlock* label_53 = BasicBlock::Create(mod->getContext(), "",func_readLine,0);
//
//  // Block  (label_53)
//  AllocaInst* ptr_input = new AllocaInst(PointerTy_2, "input", label_53);
//  ptr_input->setAlignment(8);
//  AllocaInst* ptr_str_obj = new AllocaInst(PointerTy_14, "str_obj", label_53);
//  ptr_str_obj->setAlignment(8);
//  LoadInst* ptr_54 = new LoadInst(gvar_ptr_stdin, "", false, label_53);
//  ptr_54->setAlignment(8);
//  std::vector<Value*> int64_55_params;
//  int64_55_params.push_back(ptr_input);
//  int64_55_params.push_back(const_ptr_37);
//  int64_55_params.push_back(ptr_54);
//  CallInst* int64_55 = CallInst::Create(func_getline, int64_55_params, "", label_53);
//  int64_55->setCallingConv(CallingConv::C);
//  int64_55->setTailCall(false);
//  AttributeSet int64_55_PAL;
//  int64_55->setAttributes(int64_55_PAL);
//
//  CallInst* ptr_56 = CallInst::Create(func_malloc, const_int64_38, "", label_53);
//  ptr_56->setCallingConv(CallingConv::C);
//  ptr_56->setTailCall(false);
//  AttributeSet ptr_56_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoAlias);
//     PAS = AttributeSet::get(mod->getContext(), 0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  ptr_56_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// ptr_56->setAttributes(ptr_56_PAL);
//
// CastInst* ptr_57 = new BitCastInst(ptr_56, PointerTy_14, "", label_53);
// StoreInst* void_58 = new StoreInst(ptr_57, ptr_str_obj, false, label_53);
// void_58->setAlignment(8);
// LoadInst* ptr_59 = new LoadInst(ptr_str_obj, "", false, label_53);
// ptr_59->setAlignment(8);
// GetElementPtrInst* ptr_60 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_59, {
//  const_int32_39,
//  const_int32_39
// }, "", label_53);
// CastInst* ptr_61 = new BitCastInst(ptr_60, PointerTy_23, "", label_53);
// StoreInst* void_62 = new StoreInst(const_int32_40, ptr_61, false, label_53);
// void_62->setAlignment(8);
// LoadInst* ptr_63 = new LoadInst(ptr_input, "", false, label_53);
// ptr_63->setAlignment(8);
// LoadInst* ptr_64 = new LoadInst(ptr_str_obj, "", false, label_53);
// ptr_64->setAlignment(8);
// GetElementPtrInst* ptr_65 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_64, {
//  const_int32_39,
//  const_int32_35
// }, "", label_53);
// CastInst* ptr_66 = new BitCastInst(ptr_65, PointerTy_9, "", label_53);
// StoreInst* void_67 = new StoreInst(ptr_63, ptr_66, false, label_53);
// void_67->setAlignment(8);
// LoadInst* ptr_68 = new LoadInst(ptr_str_obj, "", false, label_53);
// ptr_68->setAlignment(8);
// ReturnInst::Create(mod->getContext(), ptr_68, label_53);
//
// }
//
// // Function: readInt (func_readInt)
// {
//
//  BasicBlock* label_70 = BasicBlock::Create(mod->getContext(), "",func_readInt,0);
//
//  // Block  (label_70)
//  AllocaInst* ptr_input_71 = new AllocaInst(PointerTy_2, "input", label_70);
//  ptr_input_71->setAlignment(8);
//  AllocaInst* ptr_int_obj = new AllocaInst(PointerTy_14, "int_obj", label_70);
//  ptr_int_obj->setAlignment(8);
//  LoadInst* ptr_72 = new LoadInst(gvar_ptr_stdin, "", false, label_70);
//  ptr_72->setAlignment(8);
//  std::vector<Value*> int64_73_params;
//  int64_73_params.push_back(ptr_input_71);
//  int64_73_params.push_back(const_ptr_37);
//  int64_73_params.push_back(ptr_72);
//  CallInst* int64_73 = CallInst::Create(func_getline, int64_73_params, "", label_70);
//  int64_73->setCallingConv(CallingConv::C);
//  int64_73->setTailCall(false);
//  AttributeSet int64_73_PAL;
//  int64_73->setAttributes(int64_73_PAL);
//
//  CallInst* ptr_74 = CallInst::Create(func_malloc, const_int64_38, "", label_70);
//  ptr_74->setCallingConv(CallingConv::C);
//  ptr_74->setTailCall(false);
//  AttributeSet ptr_74_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoAlias);
//     PAS = AttributeSet::get(mod->getContext(), 0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  ptr_74_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// ptr_74->setAttributes(ptr_74_PAL);
//
// CastInst* ptr_75 = new BitCastInst(ptr_74, PointerTy_14, "", label_70);
// StoreInst* void_76 = new StoreInst(ptr_75, ptr_int_obj, false, label_70);
// void_76->setAlignment(8);
// LoadInst* ptr_77 = new LoadInst(ptr_int_obj, "", false, label_70);
// ptr_77->setAlignment(8);
// GetElementPtrInst* ptr_78 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_77, {
//  const_int32_39,
//  const_int32_39
// }, "", label_70);
// CastInst* ptr_79 = new BitCastInst(ptr_78, PointerTy_23, "", label_70);
// StoreInst* void_80 = new StoreInst(const_int32_35, ptr_79, false, label_70);
// void_80->setAlignment(8);
// LoadInst* ptr_81 = new LoadInst(ptr_input_71, "", false, label_70);
// ptr_81->setAlignment(8);
// CallInst* int32_82 = CallInst::Create(func_atoi, ptr_81, "", label_70);
// int32_82->setCallingConv(CallingConv::C);
// int32_82->setTailCall(false);
// AttributeSet int32_82_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    B.addAttribute(Attribute::ReadOnly);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  int32_82_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// int32_82->setAttributes(int32_82_PAL);
//
// CastInst* int64_83 = new SExtInst(int32_82, IntegerType::get(mod->getContext(), 64), "", label_70);
// LoadInst* ptr_84 = new LoadInst(ptr_int_obj, "", false, label_70);
// ptr_84->setAlignment(8);
// GetElementPtrInst* ptr_85 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_84, {
//  const_int32_39,
//  const_int32_35
// }, "", label_70);
// CastInst* ptr_86 = new BitCastInst(ptr_85, PointerTy_17, "", label_70);
// StoreInst* void_87 = new StoreInst(int64_83, ptr_86, false, label_70);
// void_87->setAlignment(8);
// LoadInst* ptr_88 = new LoadInst(ptr_int_obj, "", false, label_70);
// ptr_88->setAlignment(8);
// ReturnInst::Create(mod->getContext(), ptr_88, label_70);
//
// }
//
// // Function: add_str (func_add_str)
// {
//  Function::arg_iterator args = func_add_str->arg_begin();
//  Value* ptr_a = &(*args++);
//  ptr_a->setName("a");
//  Value* ptr_b = &(*args++);
//  ptr_b->setName("b");
//
//  BasicBlock* label_90 = BasicBlock::Create(mod->getContext(), "",func_add_str,0);
//
//  // Block  (label_90)
//  AllocaInst* ptr_91 = new AllocaInst(PointerTy_14, "", label_90);
//  ptr_91->setAlignment(8);
//  AllocaInst* ptr_92 = new AllocaInst(PointerTy_14, "", label_90);
//  ptr_92->setAlignment(8);
//  AllocaInst* ptr_new_str = new AllocaInst(PointerTy_2, "new_str", label_90);
//  ptr_new_str->setAlignment(8);
//  AllocaInst* ptr_sum = new AllocaInst(PointerTy_14, "sum", label_90);
//  ptr_sum->setAlignment(8);
//  StoreInst* void_93 = new StoreInst(ptr_a, ptr_91, false, label_90);
//  void_93->setAlignment(8);
//  StoreInst* void_94 = new StoreInst(ptr_b, ptr_92, false, label_90);
//  void_94->setAlignment(8);
//  LoadInst* ptr_95 = new LoadInst(ptr_91, "", false, label_90);
//  ptr_95->setAlignment(8);
//  GetElementPtrInst* ptr_96 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_95, {
//   const_int32_39,
//   const_int32_35
//  }, "", label_90);
//  CastInst* ptr_97 = new BitCastInst(ptr_96, PointerTy_9, "", label_90);
//  LoadInst* ptr_98 = new LoadInst(ptr_97, "", false, label_90);
//  ptr_98->setAlignment(8);
//  CallInst* int64_99 = CallInst::Create(func_strlen, ptr_98, "", label_90);
//  int64_99->setCallingConv(CallingConv::C);
//  int64_99->setTailCall(false);
//  AttributeSet int64_99_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoUnwind);
//     B.addAttribute(Attribute::ReadOnly);
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   int64_99_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  int64_99->setAttributes(int64_99_PAL);
//
//  LoadInst* ptr_100 = new LoadInst(ptr_92, "", false, label_90);
//  ptr_100->setAlignment(8);
//  GetElementPtrInst* ptr_101 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_100, {
//   const_int32_39,
//   const_int32_35
//  }, "", label_90);
//  CastInst* ptr_102 = new BitCastInst(ptr_101, PointerTy_9, "", label_90);
//  LoadInst* ptr_103 = new LoadInst(ptr_102, "", false, label_90);
//  ptr_103->setAlignment(8);
//  CallInst* int64_104 = CallInst::Create(func_strlen, ptr_103, "", label_90);
//  int64_104->setCallingConv(CallingConv::C);
//  int64_104->setTailCall(false);
//  AttributeSet int64_104_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoUnwind);
//     B.addAttribute(Attribute::ReadOnly);
//     PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   int64_104_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
//  }
//  int64_104->setAttributes(int64_104_PAL);
//
//  BinaryOperator* int64_105 = BinaryOperator::Create(Instruction::Add, int64_99, int64_104, "", label_90);
//  BinaryOperator* int64_106 = BinaryOperator::Create(Instruction::Add, int64_105, const_int64_41, "", label_90);
//  CallInst* ptr_107 = CallInst::Create(func_malloc, int64_106, "", label_90);
//  ptr_107->setCallingConv(CallingConv::C);
//  ptr_107->setTailCall(false);
//  AttributeSet ptr_107_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoAlias);
//     PAS = AttributeSet::get(mod->getContext(), 0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  ptr_107_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// ptr_107->setAttributes(ptr_107_PAL);
//
// StoreInst* void_108 = new StoreInst(ptr_107, ptr_new_str, false, label_90);
// void_108->setAlignment(8);
// LoadInst* ptr_109 = new LoadInst(ptr_new_str, "", false, label_90);
// ptr_109->setAlignment(8);
// LoadInst* ptr_110 = new LoadInst(ptr_91, "", false, label_90);
// ptr_110->setAlignment(8);
// GetElementPtrInst* ptr_111 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_110, {
//  const_int32_39,
//  const_int32_35
// }, "", label_90);
// CastInst* ptr_112 = new BitCastInst(ptr_111, PointerTy_9, "", label_90);
// LoadInst* ptr_113 = new LoadInst(ptr_112, "", false, label_90);
// ptr_113->setAlignment(8);
// std::vector<Value*> ptr_114_params;
// ptr_114_params.push_back(ptr_109);
// ptr_114_params.push_back(ptr_113);
// CallInst* ptr_114 = CallInst::Create(func_strcpy, ptr_114_params, "", label_90);
// ptr_114->setCallingConv(CallingConv::C);
// ptr_114->setTailCall(false);
// AttributeSet ptr_114_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  ptr_114_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// ptr_114->setAttributes(ptr_114_PAL);
//
// LoadInst* ptr_115 = new LoadInst(ptr_new_str, "", false, label_90);
// ptr_115->setAlignment(8);
// LoadInst* ptr_116 = new LoadInst(ptr_92, "", false, label_90);
// ptr_116->setAlignment(8);
// GetElementPtrInst* ptr_117 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_116, {
//  const_int32_39,
//  const_int32_35
// }, "", label_90);
// CastInst* ptr_118 = new BitCastInst(ptr_117, PointerTy_9, "", label_90);
// LoadInst* ptr_119 = new LoadInst(ptr_118, "", false, label_90);
// ptr_119->setAlignment(8);
// std::vector<Value*> ptr_120_params;
// ptr_120_params.push_back(ptr_115);
// ptr_120_params.push_back(ptr_119);
// CallInst* ptr_120 = CallInst::Create(func_strcat, ptr_120_params, "", label_90);
// ptr_120->setCallingConv(CallingConv::C);
// ptr_120->setTailCall(false);
// AttributeSet ptr_120_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  ptr_120_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// ptr_120->setAttributes(ptr_120_PAL);
//
// CallInst* ptr_121 = CallInst::Create(func_malloc, const_int64_38, "", label_90);
// ptr_121->setCallingConv(CallingConv::C);
// ptr_121->setTailCall(false);
// AttributeSet ptr_121_PAL;
// {
//  SmallVector<AttributeSet, 4> Attrs;
//  AttributeSet PAS;
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoAlias);
//    PAS = AttributeSet::get(mod->getContext(), 0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  {
//   AttrBuilder B;
//   B.addAttribute(Attribute::NoUnwind);
//   PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//  }
//
// Attrs.push_back(PAS);
// ptr_121_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// ptr_121->setAttributes(ptr_121_PAL);
//
// CastInst* ptr_122 = new BitCastInst(ptr_121, PointerTy_14, "", label_90);
// StoreInst* void_123 = new StoreInst(ptr_122, ptr_sum, false, label_90);
// void_123->setAlignment(8);
// LoadInst* ptr_124 = new LoadInst(ptr_sum, "", false, label_90);
// ptr_124->setAlignment(8);
// GetElementPtrInst* ptr_125 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_124, {
//  const_int32_39,
//  const_int32_39
// }, "", label_90);
// CastInst* ptr_126 = new BitCastInst(ptr_125, PointerTy_23, "", label_90);
// StoreInst* void_127 = new StoreInst(const_int32_40, ptr_126, false, label_90);
// void_127->setAlignment(8);
// LoadInst* ptr_128 = new LoadInst(ptr_new_str, "", false, label_90);
// ptr_128->setAlignment(8);
// LoadInst* ptr_129 = new LoadInst(ptr_sum, "", false, label_90);
// ptr_129->setAlignment(8);
// GetElementPtrInst* ptr_130 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_129, {
//  const_int32_39,
//  const_int32_35
// }, "", label_90);
// CastInst* ptr_131 = new BitCastInst(ptr_130, PointerTy_9, "", label_90);
// StoreInst* void_132 = new StoreInst(ptr_128, ptr_131, false, label_90);
// void_132->setAlignment(8);
// LoadInst* ptr_133 = new LoadInst(ptr_sum, "", false, label_90);
// ptr_133->setAlignment(8);
// ReturnInst::Create(mod->getContext(), ptr_133, label_90);
//
// }
//
// // Function: add_int (func_add_int)
// {
//  Function::arg_iterator args = func_add_int->arg_begin();
//  Value* ptr_a_135 = &(*args++);
//  ptr_a_135->setName("a");
//  Value* ptr_b_136 = &(*args++);
//  ptr_b_136->setName("b");
//
//  BasicBlock* label_137 = BasicBlock::Create(mod->getContext(), "",func_add_int,0);
//
//  // Block  (label_137)
//  AllocaInst* ptr_138 = new AllocaInst(PointerTy_14, "", label_137);
//  ptr_138->setAlignment(8);
//  AllocaInst* ptr_139 = new AllocaInst(PointerTy_14, "", label_137);
//  ptr_139->setAlignment(8);
//  AllocaInst* ptr_new_val = new AllocaInst(IntegerType::get(mod->getContext(), 64), "new_val", label_137);
//  ptr_new_val->setAlignment(8);
//  AllocaInst* ptr_sum_140 = new AllocaInst(PointerTy_14, "sum", label_137);
//  ptr_sum_140->setAlignment(8);
//  StoreInst* void_141 = new StoreInst(ptr_a_135, ptr_138, false, label_137);
//  void_141->setAlignment(8);
//  StoreInst* void_142 = new StoreInst(ptr_b_136, ptr_139, false, label_137);
//  void_142->setAlignment(8);
//  LoadInst* ptr_143 = new LoadInst(ptr_138, "", false, label_137);
//  ptr_143->setAlignment(8);
//  GetElementPtrInst* ptr_144 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_143, {
//   const_int32_39,
//   const_int32_35
//  }, "", label_137);
//  CastInst* ptr_145 = new BitCastInst(ptr_144, PointerTy_17, "", label_137);
//  LoadInst* int64_146 = new LoadInst(ptr_145, "", false, label_137);
//  int64_146->setAlignment(8);
//  LoadInst* ptr_147 = new LoadInst(ptr_139, "", false, label_137);
//  ptr_147->setAlignment(8);
//  GetElementPtrInst* ptr_148 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_147, {
//   const_int32_39,
//   const_int32_35
//  }, "", label_137);
//  CastInst* ptr_149 = new BitCastInst(ptr_148, PointerTy_17, "", label_137);
//  LoadInst* int64_150 = new LoadInst(ptr_149, "", false, label_137);
//  int64_150->setAlignment(8);
//  BinaryOperator* int64_151 = BinaryOperator::Create(Instruction::Add, int64_146, int64_150, "", label_137);
//  StoreInst* void_152 = new StoreInst(int64_151, ptr_new_val, false, label_137);
//  void_152->setAlignment(8);
//  CallInst* ptr_153 = CallInst::Create(func_malloc, const_int64_38, "", label_137);
//  ptr_153->setCallingConv(CallingConv::C);
//  ptr_153->setTailCall(false);
//  AttributeSet ptr_153_PAL;
//  {
//   SmallVector<AttributeSet, 4> Attrs;
//   AttributeSet PAS;
//    {
//     AttrBuilder B;
//     B.addAttribute(Attribute::NoAlias);
//     PAS = AttributeSet::get(mod->getContext(), 0U, B);
//    }
//
//   Attrs.push_back(PAS);
//   {
//    AttrBuilder B;
//    B.addAttribute(Attribute::NoUnwind);
//    PAS = AttributeSet::get(mod->getContext(), ~0U, B);
//   }
//
//  Attrs.push_back(PAS);
//  ptr_153_PAL = AttributeSet::get(mod->getContext(), Attrs);
//
// }
// ptr_153->setAttributes(ptr_153_PAL);
//
// CastInst* ptr_154 = new BitCastInst(ptr_153, PointerTy_14, "", label_137);
// StoreInst* void_155 = new StoreInst(ptr_154, ptr_sum_140, false, label_137);
// void_155->setAlignment(8);
// LoadInst* ptr_156 = new LoadInst(ptr_sum_140, "", false, label_137);
// ptr_156->setAlignment(8);
// GetElementPtrInst* ptr_157 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_156, {
//  const_int32_39,
//  const_int32_39
// }, "", label_137);
// CastInst* ptr_158 = new BitCastInst(ptr_157, PointerTy_23, "", label_137);
// StoreInst* void_159 = new StoreInst(const_int32_35, ptr_158, false, label_137);
// void_159->setAlignment(8);
// LoadInst* int64_160 = new LoadInst(ptr_new_val, "", false, label_137);
// int64_160->setAlignment(8);
// LoadInst* ptr_161 = new LoadInst(ptr_sum_140, "", false, label_137);
// ptr_161->setAlignment(8);
// GetElementPtrInst* ptr_162 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_161, {
//  const_int32_39,
//  const_int32_35
// }, "", label_137);
// CastInst* ptr_163 = new BitCastInst(ptr_162, PointerTy_17, "", label_137);
// StoreInst* void_164 = new StoreInst(int64_160, ptr_163, false, label_137);
// void_164->setAlignment(8);
// LoadInst* ptr_165 = new LoadInst(ptr_sum_140, "", false, label_137);
// ptr_165->setAlignment(8);
// ReturnInst::Create(mod->getContext(), ptr_165, label_137);
//
// }
//
// // Function: add_any (func_add_any)
// {
//  Function::arg_iterator args = func_add_any->arg_begin();
//  Value* ptr_a_167 = &(*args++);
//  ptr_a_167->setName("a");
//  Value* ptr_b_168 = &(*args++);
//  ptr_b_168->setName("b");
//
//  BasicBlock* label_169 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_170 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_171 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_172 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_173 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_174 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_175 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_176 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_177 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//  BasicBlock* label_178 = BasicBlock::Create(mod->getContext(), "",func_add_any,0);
//
//  // Block  (label_169)
//  AllocaInst* ptr_179 = new AllocaInst(PointerTy_14, "", label_169);
//  ptr_179->setAlignment(8);
//  AllocaInst* ptr_180 = new AllocaInst(PointerTy_14, "", label_169);
//  ptr_180->setAlignment(8);
//  AllocaInst* ptr_181 = new AllocaInst(PointerTy_14, "", label_169);
//  ptr_181->setAlignment(8);
//  StoreInst* void_182 = new StoreInst(ptr_a_167, ptr_180, false, label_169);
//  void_182->setAlignment(8);
//  StoreInst* void_183 = new StoreInst(ptr_b_168, ptr_181, false, label_169);
//  void_183->setAlignment(8);
//  LoadInst* ptr_184 = new LoadInst(ptr_180, "", false, label_169);
//  ptr_184->setAlignment(8);
//  GetElementPtrInst* ptr_185 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_184, {
//   const_int32_39,
//   const_int32_39
//  }, "", label_169);
//  CastInst* ptr_186 = new BitCastInst(ptr_185, PointerTy_23, "", label_169);
//  LoadInst* int32_187 = new LoadInst(ptr_186, "", false, label_169);
//  int32_187->setAlignment(8);
//  ICmpInst* int1_188 = new ICmpInst(*label_169, ICmpInst::ICMP_EQ, int32_187, const_int32_35, "");
//  BranchInst::Create(label_170, label_172, int1_188, label_169);
//
//  // Block  (label_170)
//  LoadInst* ptr_190 = new LoadInst(ptr_181, "", false, label_170);
//  ptr_190->setAlignment(8);
//  GetElementPtrInst* ptr_191 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_190, {
//   const_int32_39,
//   const_int32_39
//  }, "", label_170);
//  CastInst* ptr_192 = new BitCastInst(ptr_191, PointerTy_23, "", label_170);
//  LoadInst* int32_193 = new LoadInst(ptr_192, "", false, label_170);
//  int32_193->setAlignment(8);
//  ICmpInst* int1_194 = new ICmpInst(*label_170, ICmpInst::ICMP_EQ, int32_193, const_int32_35, "");
//  BranchInst::Create(label_171, label_172, int1_194, label_170);
//
//  // Block  (label_171)
//  LoadInst* ptr_196 = new LoadInst(ptr_180, "", false, label_171);
//  ptr_196->setAlignment(8);
//  LoadInst* ptr_197 = new LoadInst(ptr_181, "", false, label_171);
//  ptr_197->setAlignment(8);
//  std::vector<Value*> ptr_198_params;
//  ptr_198_params.push_back(ptr_196);
//  ptr_198_params.push_back(ptr_197);
//  CallInst* ptr_198 = CallInst::Create(func_add_int, ptr_198_params, "", label_171);
//  ptr_198->setCallingConv(CallingConv::C);
//  ptr_198->setTailCall(false);
//  AttributeSet ptr_198_PAL;
//  ptr_198->setAttributes(ptr_198_PAL);
//
//  StoreInst* void_199 = new StoreInst(ptr_198, ptr_179, false, label_171);
//  void_199->setAlignment(8);
//  BranchInst::Create(label_178, label_171);
//
//  // Block  (label_172)
//  LoadInst* ptr_201 = new LoadInst(ptr_180, "", false, label_172);
//  ptr_201->setAlignment(8);
//  GetElementPtrInst* ptr_202 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_201, {
//   const_int32_39,
//   const_int32_39
//  }, "", label_172);
//  CastInst* ptr_203 = new BitCastInst(ptr_202, PointerTy_23, "", label_172);
//  LoadInst* int32_204 = new LoadInst(ptr_203, "", false, label_172);
//  int32_204->setAlignment(8);
//  ICmpInst* int1_205 = new ICmpInst(*label_172, ICmpInst::ICMP_EQ, int32_204, const_int32_40, "");
//  BranchInst::Create(label_173, label_175, int1_205, label_172);
//
//  // Block  (label_173)
//  LoadInst* ptr_207 = new LoadInst(ptr_181, "", false, label_173);
//  ptr_207->setAlignment(8);
//  GetElementPtrInst* ptr_208 = GetElementPtrInst::Create(StructTy_struct_Object, ptr_207, {
//   const_int32_39,
//   const_int32_39
//  }, "", label_173);
//  CastInst* ptr_209 = new BitCastInst(ptr_208, PointerTy_23, "", label_173);
//  LoadInst* int32_210 = new LoadInst(ptr_209, "", false, label_173);
//  int32_210->setAlignment(8);
//  ICmpInst* int1_211 = new ICmpInst(*label_173, ICmpInst::ICMP_EQ, int32_210, const_int32_40, "");
//  BranchInst::Create(label_174, label_175, int1_211, label_173);
//
//  // Block  (label_174)
//  LoadInst* ptr_213 = new LoadInst(ptr_180, "", false, label_174);
//  ptr_213->setAlignment(8);
//  LoadInst* ptr_214 = new LoadInst(ptr_181, "", false, label_174);
//  ptr_214->setAlignment(8);
//  std::vector<Value*> ptr_215_params;
//  ptr_215_params.push_back(ptr_213);
//  ptr_215_params.push_back(ptr_214);
//  CallInst* ptr_215 = CallInst::Create(func_add_str, ptr_215_params, "", label_174);
//  ptr_215->setCallingConv(CallingConv::C);
//  ptr_215->setTailCall(false);
//  AttributeSet ptr_215_PAL;
//  ptr_215->setAttributes(ptr_215_PAL);
//
//  StoreInst* void_216 = new StoreInst(ptr_215, ptr_179, false, label_174);
//  void_216->setAlignment(8);
//  BranchInst::Create(label_178, label_174);
//
//  // Block  (label_175)
//  /*CallInst* void_218 = CallInst::Create(func_error, const_ptr_42, "", label_175);
//  void_218->setCallingConv(CallingConv::C);
//  void_218->setTailCall(false);
//  AttributeSet void_218_PAL;
//  void_218->setAttributes(void_218_PAL);
//  */
//  BranchInst::Create(label_176, label_175);
//
//  // Block  (label_176)
//  BranchInst::Create(label_177, label_176);
//
//  // Block  (label_177)
//  StoreInst* void_221 = new StoreInst(const_ptr_43, ptr_179, false, label_177);
//  void_221->setAlignment(8);
//  BranchInst::Create(label_178, label_177);
//
//  // Block  (label_178)
//  LoadInst* ptr_223 = new LoadInst(ptr_179, "", false, label_178);
//  ptr_223->setAlignment(8);
//  ReturnInst::Create(mod->getContext(), ptr_223, label_178);
//
// }
//
// return mod;
// }
